services:
  react_app:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "corepack enable && pnpm install && pnpm dev --host"
    environment:
      - HOST=0.0.0.0
